language: node_js
node_js:
  - "13"
env:
  global:
    - CI=1
# headless-gl deps must be installed, not run.
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - xutils-dev
    - libxi-dev
    - libxxf86vm-dev
    - x11proto-xf86vidmode-dev
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
install:
  - npm i -g lerna
  - lerna bootstrap
before_script:
  - npm run dist
# omit 'ao', as GPU functions don't work in CI.
script:
  - lerna run test --ignore @gltf-transform/ao --ignore @gltf-transform/atlas
