language: node_js
# Better headless-gl support on macOS.
os: osx
node_js:
  # Latest prebuilt binary from https://github.com/stackgl/headless-gl/releases.
  - "12"
env:
  global:
    - CI=1
before_script:
  - yarn run dist
script:
  - yarn test
after_success:
  - yarn run coverage:report
