language: node_js
node_js:
  - "10"
env:
  global:
    - CI=1
install:
  - npm i -g lerna
  - lerna bootstrap --ignore @gltf-transform/ao --ignore @gltf-transform/cli
before_script:
  - npm run dist
script:
  - lerna run test --ignore @gltf-transform/ao --ignore @gltf-transform/cli
